version: '3.3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_USER: testuser
    ports:
      - "5432:5432"
    container_name: postgres_container
    volumes:
      - ./initdb/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: database2
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: tetspass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql

volumes:
  postgres_data:
  mysql_data: