server:
  port: 8080

spring:
  application:
    name: user-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

logging:
  level:
    sql: debug
    root: debug
    web: debug